// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_application_1/models/measurement.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MeasurementAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MeasurementAdapter());
  }
}
